#!/bin/bash
echo "Este script te permitirá habilitar tu USUARIO ROOT"
echo "Iniciando"
sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
echo '
Port 22
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
' >> /etc/ssh/sshd_config
' >> /etc/ssh/ssh_config
' >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
service ssh restart
service sshd restart
echo "Ahora agregaremos un password a tu cuenta root"
passwd root
echo "Listo!!"
rm root
