#!/bin/bash
echo "Este script habilitara ROOT"
echo "Iniciando"
sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config
sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config
echo '
Port 22
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
' >> /etc/ssh/sshd_config
' >> /etc/ssh/ssh_config
service ssh restart
service sshd restart
echo "Agregue un password al uset root"
passwd root
echo "Listo!! 😃"
rm root
