#!/bin/bash
echo "Este Script habilitara ROOT en OC"
echo "Iniciando"
sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
sed -i '/PermitRootLogin/d' /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
echo '
Port 22
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication yes
' >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
service ssh restart
service sshd restart
echo "AGREGUE PASSWORD"
passwd root
echo "Listo!! 😸"
rm root2
